<script setup lang="ts">
import { h } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { createColumnHelper, FlexRender, getCoreRowModel, useVueTable } from '@tanstack/vue-table'
import { Fingerprint, RefreshCw, ShieldCheck } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue';import StatusBadge from '@/components/ui/StatusBadge.vue';import { getAudit,type AuditEntry } from '@/lib/api'
const query=useQuery({queryKey:['audit'],queryFn:getAudit,refetchInterval:15000});const column=createColumnHelper<AuditEntry>();const columns=[column.accessor('occurred_at',{header:'Timestamp',cell:i=>new Date(i.getValue()).toLocaleString('pt-BR')}),column.accessor('actor_email',{header:'Actor',cell:i=>i.getValue()||'system'}),column.accessor('action',{header:'Action'}),column.accessor('target_name',{header:'Target',cell:i=>i.getValue()||'—'}),column.accessor('risk',{header:'Risk',cell:i=>h(StatusBadge,{status:i.getValue()==='critical'?'critical':i.getValue()==='dangerous'?'warning':'info',label:i.getValue()})}),column.accessor('decision',{header:'Decision',cell:i=>h(StatusBadge,{status:i.getValue()==='allowed'?'healthy':'critical',label:i.getValue()})})];const table=useVueTable({get data(){return query.data.value??[]},columns,getCoreRowModel:getCoreRowModel()})
</script>
<template><div class="mx-auto max-w-[1680px] space-y-5"><header class="flex items-end justify-between"><div><div class="flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-signal"><ShieldCheck class="h-3.5 w-3.5"/>Hash-chained evidence</div><h1 class="mt-3 text-3xl font-semibold tracking-tight">Audit trail</h1><p class="mt-2 text-sm text-muted">Decisões, autenticações e mutações registradas em ordem verificável.</p></div><Button variant="outline" @click="query.refetch()"><RefreshCw class="h-4 w-4"/>Atualizar</Button></header><section class="overflow-hidden rounded-xl border border-line bg-panel/65"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead class="border-b border-line bg-slate-950/35 font-mono text-[9px] uppercase tracking-[.16em] text-muted"><tr v-for="group in table.getHeaderGroups()" :key="group.id"><th v-for="header in group.headers" :key="header.id" class="px-4 py-3"><FlexRender :render="header.column.columnDef.header" :props="header.getContext()"/></th></tr></thead><tbody class="divide-y divide-line/60"><tr v-for="row in table.getRowModel().rows" :key="row.id" class="text-xs text-slate-300 transition-colors hover:bg-white/[.02]"><td v-for="cell in row.getVisibleCells()" :key="cell.id" class="px-4 py-3.5"><FlexRender :render="cell.column.columnDef.cell" :props="cell.getContext()"/></td></tr></tbody></table><div v-if="!query.data.value?.length" class="grid min-h-64 place-items-center text-center"><div><Fingerprint class="mx-auto h-7 w-7 text-muted"/><p class="mt-3 text-sm text-muted">Nenhum evento auditado.</p></div></div></div></section></div></template>

