<script setup lang="ts">
import { ref } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { CheckCircle2, CloudCog, EyeOff, KeyRound, Plus, RefreshCw, ShieldCheck, X } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'
import { createIntegration, getIntegrations } from '@/lib/api'

const providers=[{id:'proxmox',label:'Proxmox',hint:'Scoped API token'},{id:'docker',label:'Docker',hint:'mTLS agent / socket proxy'},{id:'kubernetes',label:'Kubernetes',hint:'Scoped service account'},{id:'github',label:'GitHub',hint:'Fine-grained token / App'},{id:'cloudflare',label:'Cloudflare',hint:'Scoped API token'},{id:'oracle',label:'Oracle Cloud',hint:'API signing key'},{id:'terraform',label:'Terraform',hint:'Ephemeral worker credentials'}]
const client=useQueryClient();const query=useQuery({queryKey:['integrations'],queryFn:getIntegrations});const modal=ref(false);const error=ref('');const form=ref({name:'',provider:'proxmox'})
const create=useMutation({mutationFn:()=>createIntegration({name:form.value.name,provider:form.value.provider,config:{credential_state:'not_configured'}}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['integrations']});modal.value=false;form.value={name:'',provider:'proxmox'}},onError:(value:any)=>error.value=value?.response?.data?.error?.message??'Não foi possível registrar a integração.'})
const status=(value:string)=>value==='connected'?'healthy':value==='error'?'critical':'warning'
</script>
<template><div class="mx-auto max-w-[1680px] space-y-5"><header class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div class="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-signal"><CloudCog class="h-3.5 w-3.5"/>Credential-safe adapters</div><h1 class="mt-3 text-3xl font-semibold tracking-tight">Integrations center</h1><p class="mt-2 text-sm text-muted">Conexões, postura de credenciais e saúde dos adapters sem exposição de valores sensíveis.</p></div><div class="flex gap-2"><Button variant="outline" @click="query.refetch()"><RefreshCw class="h-4 w-4"/>Atualizar</Button><Button @click="modal=true"><Plus class="h-4 w-4"/>Nova integração</Button></div></header>
<section class="grid gap-4 md:grid-cols-3"><article class="rounded-xl border border-line bg-panel/65 p-5"><ShieldCheck class="h-5 w-5 text-signal"/><p class="mt-4 font-mono text-2xl text-white">{{query.data.value?.filter(item=>item.status==='connected').length??0}}</p><p class="mt-1 text-xs text-muted">Conectadas e saudáveis</p></article><article class="rounded-xl border border-line bg-panel/65 p-5"><KeyRound class="h-5 w-5 text-warning"/><p class="mt-4 font-mono text-2xl text-white">{{query.data.value?.filter(item=>item.status==='pending').length??0}}</p><p class="mt-1 text-xs text-muted">Aguardando credenciais</p></article><article class="rounded-xl border border-line bg-panel/65 p-5"><EyeOff class="h-5 w-5 text-pulse"/><p class="mt-4 font-mono text-2xl text-white">0</p><p class="mt-1 text-xs text-muted">Segredos expostos no browser</p></article></section>
<div v-if="query.isError.value" class="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">Não foi possível carregar as integrações.</div><section v-else class="grid gap-4 lg:grid-cols-2"><article v-for="integration in query.data.value" :key="integration.id" class="rounded-xl border border-line bg-panel/65 p-5"><div class="flex items-start gap-4"><div class="grid h-11 w-11 place-items-center rounded-xl border border-line bg-slate-950/50"><CloudCog class="h-5 w-5 text-slate-300"/></div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-sm font-medium text-slate-100">{{integration.name}}</h2><StatusBadge :status="status(integration.status)" :label="integration.status"/></div><p class="mt-1 font-mono text-[10px] uppercase tracking-wider text-muted">{{integration.provider}}</p></div></div><div class="mt-5 grid gap-3 border-t border-line pt-4 sm:grid-cols-2"><div><p class="font-mono text-[9px] uppercase tracking-wider text-muted">Credential state</p><p class="mt-2 flex items-center gap-2 text-xs text-slate-300"><EyeOff class="h-3.5 w-3.5 text-signal"/>Valores sempre mascarados</p></div><div><p class="font-mono text-[9px] uppercase tracking-wider text-muted">Last health check</p><p class="mt-2 text-xs text-slate-300">{{integration.last_checked_at?new Date(integration.last_checked_at).toLocaleString('pt-BR'):'Ainda não executado'}}</p></div></div><div v-if="Object.keys(integration.config??{}).length" class="mt-4 flex flex-wrap gap-1.5"><span v-for="key in Object.keys(integration.config)" :key="key" class="rounded border border-line px-2 py-1 font-mono text-[9px] text-muted">{{key}}: ••••••••</span></div></article><div v-if="!query.isLoading.value&&!query.data.value?.length" class="col-span-full grid min-h-64 place-items-center rounded-xl border border-dashed border-line text-center"><div><CloudCog class="mx-auto h-7 w-7 text-muted"/><p class="mt-3 text-sm text-muted">Nenhuma integração registrada.</p><Button class="mt-4" @click="modal=true"><Plus class="h-4 w-4"/>Começar</Button></div></div></section>
<section class="rounded-xl border border-line bg-panel/45 p-5"><h2 class="text-sm font-medium">Catálogo de providers</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div v-for="provider in providers" :key="provider.id" class="rounded-lg border border-line bg-slate-950/30 p-3"><p class="flex items-center gap-2 text-xs text-slate-200"><CheckCircle2 class="h-3.5 w-3.5 text-signal"/>{{provider.label}}</p><p class="mt-2 text-[10px] text-muted">{{provider.hint}}</p></div></div></section>
<div v-if="modal" class="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" @click.self="modal=false"><form class="w-full max-w-md rounded-xl border border-line bg-[#0b111d] p-6" @submit.prevent="create.mutate()"><header class="flex items-start"><div><p class="font-mono text-[10px] uppercase tracking-widest text-signal">Adapter metadata</p><h2 class="mt-2 text-xl font-semibold">Registrar integração</h2></div><button type="button" class="ml-auto cursor-pointer p-2 text-muted" @click="modal=false"><X class="h-4 w-4"/></button></header><div class="mt-6 space-y-4"><label class="block text-xs">Nome<input v-model="form.name" required class="field" placeholder="Proxmox Homelab"/></label><label class="block text-xs">Provider<select v-model="form.provider" class="field"><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{provider.label}}</option></select></label><div class="rounded-lg border border-signal/15 bg-signal/[.04] p-3 text-[11px] leading-5 text-muted"><strong class="text-signal">Fluxo seguro:</strong> este passo salva apenas metadados. Tokens e chaves devem ser injetados pelo mecanismo de secrets do ambiente; eles nunca são exibidos ou reenviados pelo browser.</div></div><p v-if="error" class="mt-4 text-xs text-danger">{{error}}</p><Button class="mt-6 w-full" type="submit">Registrar metadados</Button></form></div></div></template>
