<script setup lang="ts">
import { computed } from 'vue'
import { Boxes, Construction, LockKeyhole, ShieldCheck } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'
const props = defineProps<{ module: string }>()
const title = computed(()=>({cloud:'Oracle / Cloud',kubernetes:'K3s / Kubernetes','remote-access':'Remote Access',audit:'Audit Logs'}[props.module] ?? props.module.charAt(0).toUpperCase()+props.module.slice(1)))
</script>
<template><div class="mx-auto max-w-[1680px]"><div class="flex flex-col justify-between gap-4 border-b border-line pb-6 md:flex-row md:items-end"><div><StatusBadge status="info" label="Adapter contract ready" /><h1 class="mt-4 text-3xl font-semibold tracking-tight">{{title}}</h1><p class="mt-2 max-w-2xl text-sm text-muted">Módulo operacional preparado para conexão segura com credenciais e permissões mínimas.</p></div><Button variant="outline"><LockKeyhole class="h-4 w-4"/>Configurar integração</Button></div><section class="mt-6 grid gap-4 lg:grid-cols-[1fr_380px]"><article class="flex min-h-[420px] flex-col items-center justify-center rounded-xl border border-dashed border-line bg-panel/35 p-8 text-center"><div class="grid h-14 w-14 place-items-center rounded-2xl border border-pulse/20 bg-pulse/[.07]"><Construction class="h-6 w-6 text-pulse"/></div><h2 class="mt-5 text-lg font-medium">Control surface reserved</h2><p class="mt-2 max-w-md text-sm leading-relaxed text-muted">O contrato de domínio existe no backend. Conecte o adapter para trocar este estado vazio por recursos, ações, telemetria e auditoria reais.</p></article><aside class="space-y-3"><div class="rounded-xl border border-signal/15 bg-signal/[.035] p-5"><div class="flex items-center gap-2 text-signal"><ShieldCheck class="h-4 w-4"/><h2 class="text-sm font-medium">Policy boundary active</h2></div><p class="mt-3 text-xs leading-relaxed text-muted">Toda ação deste módulo será classificada como local, remota ou cloud antes da execução.</p></div><div class="rounded-xl border border-line bg-panel/60 p-5"><div class="flex items-center gap-2"><Boxes class="h-4 w-4 text-slate-400"/><h2 class="text-sm font-medium">Module contract</h2></div><dl class="mt-4 space-y-3 font-mono text-[10px]"><div class="flex justify-between"><dt class="text-muted">STATUS</dt><dd class="text-warning">AWAITING_CONFIG</dd></div><div class="flex justify-between"><dt class="text-muted">AUDIT</dt><dd class="text-signal">ENFORCED</dd></div><div class="flex justify-between"><dt class="text-muted">RBAC</dt><dd class="text-signal">ENFORCED</dd></div></dl></div></aside></section></div>
</template>

