<script setup lang="ts">
import { computed, ref } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { Boxes, Database, MemoryStick, Play, Power, RefreshCw, RotateCcw, Server, ShieldCheck, Square } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'
import { getJobs, getProxmoxInventory, getProxmoxSummary, runProxmoxPowerAction, syncProxmox, type ProxmoxGuest } from '@/lib/api'

type Tab='qemu'|'lxc'|'storage'
const tab=ref<Tab>('qemu')
const client=useQueryClient()
const summary=useQuery({queryKey:['proxmox-summary'],queryFn:getProxmoxSummary,refetchInterval:15000})
const inventory=useQuery({queryKey:['proxmox-inventory'],queryFn:getProxmoxInventory,refetchInterval:20000})
const jobs=useQuery({queryKey:['jobs'],queryFn:getJobs,refetchInterval:3000})
const sync=useMutation({mutationFn:syncProxmox,onSuccess:()=>{client.invalidateQueries({queryKey:['jobs']});setTimeout(()=>{client.invalidateQueries({queryKey:['proxmox-summary']});client.invalidateQueries({queryKey:['proxmox-inventory']})},2500)}})
const power=useMutation({mutationFn:(input:{guest:ProxmoxGuest;action:'start'|'stop'|'shutdown'|'reboot'|'reset'})=>runProxmoxPowerAction(input.guest.node,input.guest.type,input.guest.vmid,input.action),onSuccess:()=>setTimeout(()=>client.invalidateQueries({queryKey:['proxmox-inventory']}),1200)})
const lastJob=computed(()=>jobs.data.value?.find(job=>job.kind==='proxmox.sync'))
const guests=computed(()=>tab.value==='qemu'?(inventory.data.value?.virtual_machines??[]):(inventory.data.value?.containers??[]))
const formatBytes=(value=0)=>{if(!value)return'0 B';const units=['B','KB','MB','GB','TB'],index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return`${(value/1024**index).toFixed(index>2?1:0)} ${units[index]}`}
const uptime=(seconds=0)=>`${Math.floor(seconds/86400)}d ${Math.floor(seconds%86400/3600)}h`
const execute=(guest:ProxmoxGuest,action:'start'|'stop'|'shutdown'|'reboot'|'reset')=>{if(window.confirm(`Confirma ${action} em ${guest.type.toUpperCase()} ${guest.vmid} (${guest.name})?`))power.mutate({guest,action})}
</script>

<template>
  <div class="mx-auto max-w-[1680px] space-y-5">
    <header class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div class="flex flex-wrap gap-2"><StatusBadge :status="inventory.isError.value?'critical':'healthy'" :label="inventory.isError.value?'provider unavailable':'cluster administrator'"/><span class="inline-flex items-center gap-1.5 font-mono text-[10px] uppercase text-signal"><ShieldCheck class="h-3.5 w-3.5"/>PVE API token · audited operations</span></div><h1 class="mt-4 text-3xl font-semibold">Proxmox fabric</h1><p class="mt-2 text-sm text-muted">Nodes, QEMU, LXC, storage e controle de energia diretamente pela API PVE.</p></div><Button :disabled="!summary.data.value?.configured||sync.isPending.value" @click="sync.mutate()"><RefreshCw :class="['h-4 w-4',sync.isPending.value&&'animate-spin']"/>Sincronizar</Button></header>
    <div v-if="inventory.isError.value||power.isError.value" class="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">A operação Proxmox falhou. Confirme ACL do token, node e estado atual do guest.</div>
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article v-for="item in [{label:'Nodes',value:inventory.data.value?.nodes.length??0,icon:Server},{label:'QEMU VMs',value:inventory.data.value?.virtual_machines.length??0,icon:Boxes},{label:'LXC containers',value:inventory.data.value?.containers.length??0,icon:Database},{label:'Storage pools',value:inventory.data.value?.storage.length??0,icon:MemoryStick}]" :key="item.label" class="rounded-xl border border-line bg-panel/65 p-5"><component :is="item.icon" class="h-4 w-4 text-muted"/><p class="mt-5 font-mono text-2xl text-white">{{item.value}}</p><p class="mt-1 text-xs text-muted">{{item.label}}</p></article></section>
    <section class="grid gap-5 xl:grid-cols-[1fr_320px]">
      <div class="space-y-5">
        <article class="overflow-hidden rounded-xl border border-line bg-panel/65"><header class="border-b border-line p-4"><h2 class="text-sm font-medium">Cluster nodes</h2></header><div class="grid gap-px bg-line/60 md:grid-cols-2"><div v-for="node in inventory.data.value?.nodes" :key="node.node" class="bg-panel p-4"><div class="flex items-center justify-between"><div><p class="text-sm text-slate-200">{{node.node}}</p><p class="mt-1 font-mono text-[9px] text-muted">{{node.maxcpu}} CPU · {{formatBytes(node.maxmem)}} · {{uptime(node.uptime)}}</p></div><StatusBadge :status="node.status==='online'?'healthy':'critical'" :label="node.status"/></div><div class="mt-4 grid grid-cols-2 gap-3 text-[10px]"><span class="text-muted">CPU <b class="float-right text-slate-300">{{(node.cpu*100).toFixed(1)}}%</b></span><span class="text-muted">RAM <b class="float-right text-slate-300">{{node.maxmem?((node.mem/node.maxmem)*100).toFixed(1):0}}%</b></span></div></div></div></article>
        <article class="overflow-hidden rounded-xl border border-line bg-panel/65"><header class="flex items-center justify-between border-b border-line p-4"><div><h2 class="text-sm font-medium">Resources</h2><p class="mt-1 text-[10px] text-muted">Snapshot {{inventory.data.value?new Date(inventory.data.value.captured_at).toLocaleString('pt-BR'):'—'}}</p></div><nav class="flex rounded-lg border border-line p-1"><button v-for="item in [{id:'qemu',label:'QEMU'},{id:'lxc',label:'LXC'},{id:'storage',label:'Storage'}]" :key="item.id" :class="['rounded px-3 py-1.5 text-xs',tab===item.id?'bg-signal/10 text-signal':'text-muted']" @click="tab=item.id as Tab">{{item.label}}</button></nav></header>
          <div v-if="tab!=='storage'" class="divide-y divide-line/60"><div v-for="guest in guests" :key="`${guest.type}-${guest.vmid}`" class="grid gap-4 p-4 lg:grid-cols-[1fr_200px_310px] lg:items-center"><div><p class="text-sm text-slate-200">{{guest.vmid}} · {{guest.name||'unnamed'}}</p><p class="mt-1 font-mono text-[9px] text-muted">{{guest.node}} · {{guest.cpus}} CPU · {{formatBytes(guest.maxmem)}} RAM · {{formatBytes(guest.maxdisk)}} disk · {{uptime(guest.uptime)}}</p></div><div><StatusBadge :status="guest.status==='running'?'healthy':'warning'" :label="guest.status"/><p class="mt-2 font-mono text-[9px] text-muted">CPU {{(guest.cpu*100).toFixed(1)}}% · MEM {{guest.maxmem?((guest.mem/guest.maxmem)*100).toFixed(1):0}}%</p></div><div class="flex flex-wrap justify-end gap-2"><Button v-if="guest.status!=='running'" variant="outline" :disabled="power.isPending.value" @click="execute(guest,'start')"><Play class="h-3.5 w-3.5"/>Start</Button><template v-else><Button variant="outline" :disabled="power.isPending.value" @click="execute(guest,'reboot')"><RotateCcw class="h-3.5 w-3.5"/>Reboot</Button><Button variant="outline" :disabled="power.isPending.value" @click="execute(guest,'shutdown')"><Power class="h-3.5 w-3.5"/>Shutdown</Button><Button variant="danger" :disabled="power.isPending.value" @click="execute(guest,'stop')"><Square class="h-3.5 w-3.5"/>Stop</Button></template></div></div><p v-if="!guests.length" class="p-10 text-center text-sm text-muted">Nenhum recurso retornado.</p></div>
          <div v-else class="divide-y divide-line/60"><div v-for="store in inventory.data.value?.storage" :key="`${store.node}-${store.storage}`" class="grid gap-3 p-4 md:grid-cols-[1fr_180px_180px]"><div><p class="text-sm text-slate-200">{{store.storage}}</p><p class="mt-1 font-mono text-[9px] text-muted">{{store.node}} · {{store.type}} · {{store.shared?'shared':'local'}}</p></div><StatusBadge :status="store.active?'healthy':'critical'" :label="store.status"/><p class="font-mono text-xs text-muted">{{formatBytes(store.used)}} / {{formatBytes(store.total)}} ({{store.total?((store.used/store.total)*100).toFixed(1):0}}%)</p></div></div>
        </article>
      </div>
      <aside class="rounded-xl border border-line bg-panel/50 p-5"><p class="font-mono text-[9px] uppercase tracking-widest text-muted">Last sync job</p><div v-if="lastJob" class="mt-4"><StatusBadge :status="lastJob.status==='succeeded'?'healthy':lastJob.status==='failed'?'critical':'info'" :label="lastJob.status"/><p class="mt-4 break-all font-mono text-[10px] text-muted">{{lastJob.id}}</p><p class="mt-2 text-xs text-slate-300">Tentativa {{lastJob.attempts}} / {{lastJob.max_attempts}}</p><p v-if="lastJob.last_error" class="mt-3 text-xs leading-5 text-danger">{{lastJob.last_error}}</p></div><p v-else class="mt-4 text-xs text-muted">Nenhum sync enfileirado.</p></aside>
    </section>
  </div>
</template>
